### ISSUE TITLE
Variables disappearing in long running scripts

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#655]
I have noticed a weird behaviour that occurs in long running scripts that have lots of memory churn.  What happens is that a loop will work successfully for several 10's of thousands of iterations, and then it will error out that an operator is not appropriate.  The line of code is one that was successfully run previously, but at this iteration it simply broke.

This is a tricky bug to isolate and reproduce because it is intermittent and non-deterministic.

Here is an example:

bsh.EvalError: Sourced file: xxxxxxxxxxx.bsh : Unary operation "++" inappropriate for object : at Line: 976 : in file: xxxxxxxxxxxxxx.bsh : ) { 

The line in question in:
```java
   for (int k=0; k<inputs.length; k++) {  // line 976
```
This loop was repeating after 15 minutes of processing when the error occurred.

Here is another example:
bsh.EvalError: Sourced file: xxxxxxxxxx.bsh : Not an array or List type : at Line: 380 : in file: xxxxxxxxxxxxxx.bsh : [ i ] 

The code for this line is:
```java
Object yield(int year, double ba,double qmd, double cag, double cbg, double cinv, double vlog,
             double[] oh, double[] df, double[] oc, double[] ce, double[] ww, double[] pn) {

   for (int i=0; i<4; i++) {
      oh[i] *= (1-0.11);  // line 380
      df[i] *= (1-0.07);
      oc[i] *= (1-0.08);
      ce[i] *= (1-0.11);
      ww[i] *= (1-0.1);
      pn[i] *= (1-0.07);
   }
```
There is only one call site for this scripted object and it calls the object ten's of thousands of times successfully, and then boom it fails.

When I look at what is going on with the debugger it turns out that the lookup of the ```k``` or ```oh``` variables is returning void, where in previous iterations the object was found correctly.  I suspect that this has something to do with the [ReferenceCache](https://github.com/beanshell/beanshell/blob/master/src/main/java/bsh/util/ReferenceCache.java) that uses weak references to [BlockNameSpace](https://github.com/beanshell/beanshell/blob/a36bd52b5037ae9b442a077888a5e4874ac03ce0/src/main/java/bsh/BSHBlock.java#L43) objects and they are getting cleared too soon, but this is guessing.  I am having a difficult time confirming this because of the nondeterminism and length of time it takes for the error to show up.  By the time that the exception happens the 'cause' has already happened elsewhere.

Here is another one, I suppose that this is related:
bsh.EvalError: Sourced file: xxxxxxxx.bsh : Undefined argument: i  : at Line: 739 : in file: xxxxxxxx.bsh : ( i ) 

The code for this line is
```java
      for (int i=0; i<yields.size(); i++) {
         y = yields.get(i);  // line 739
```

All of these errors have shown up running the same script.  Execution of long running scripts is like a box of chocolates: you never know what your gonna get.  I am still digging in and trying to figure all of these out.  I am posting this here in case anyone else has seem something like this and has any suggestions.

By the way, this is a script that successfully runs to completion using BeanShell 2.0b5.

**Comment by nickl-** [comment]
So the suggested fix [from the namespace leak issue](https://github.com/beanshell/beanshell/commit/32e8be51001be388743dac45376a699c9549c41a#r91461392) resolves this?

I am assuming 4 iterations is not enough to reproduce the line 380 issue?

**Comment by opeongo** [comment]
1) Fixing the leak issue does not help.  I may have stated it wrong, it is leaking reference objects not BlockNameSpace objects.  Regardless of fixing the leak the error still happens.

2) The [scripted object](https://beanshell.github.io/manual/quickstart.html#Scripted_Objects) named `yield` gets called 100,000's of times, and each time it returns `this` the reference to the block.  It is only called from one call site.  At that call site `oh` is always initialized with an array length 4.  For the first 10,000's of times it works fine.  Then it doesn't.  I used a debugger and paused the Java code at the exception to see what was happening.  The value of the `oh` object was the special primitive void.  I do not see how this is possible because the call site looks like:
```java
            t.yields.add(yield(year,
                               getVal(as,row, baPos),
                               getVal(as,row, qmdPos),
                               getVal(as,row, grAGPos),
                               getVal(as,row, grBGPos),
                               getVal(as,row, cInvPos),
                               getVal(as,row, yvlogPos),
                               new double[] {getVal(as,row, oh1Pos), getVal(as,row, oh2Pos), getVal(as,row, oh3Pos), getVal(as,row, oh4Pos)},
                               new double[] {getVal(as,row, df1Pos), getVal(as,row, df2Pos), getVal(as,row, df3Pos), getVal(as,row, df4Pos)},
                               new double[] {getVal(as,row, oc1Pos), getVal(as,row, oc2Pos), getVal(as,row, oc3Pos), getVal(as,row, oc4Pos)},
                               new double[] {getVal(as,row, ce1Pos), getVal(as,row, ce2Pos), getVal(as,row, ce3Pos), getVal(as,row, ce4Pos)},
                               new double[] {getVal(as,row, ww1Pos), getVal(as,row, ww2Pos), getVal(as,row, ww3Pos), getVal(as,row, ww4Pos)},
                               new double[] {getVal(as,row, pn1Pos), getVal(as,row, pn2Pos), getVal(as,row, pn3Pos), getVal(as,row, pn4Pos)}));
```

I cannot set a breakpoint to stop just before the error because it is non-deterministic and blows up at different points each time I run it.  I can stop where the exception is caught but by that point I don't know why the namespace has name entries that have void values.  Maybe from the debugger I can navigate up the call stack and see where things went wrong.

3) Million dollar question agreed.  We need a small self contained correct example.  I will see if I can come up with one.  My app churns through a lot of data making many short lived objects.  I make use of scripted objects so hundreds of thousands of namespaces coming and going.  It is a data processing application so it just keeps doing the same thing over and over as it reads through records.  It works for a long while and then stops working.

4) Yes I also think it must have more to do with memory/GC than the number of iterations.  It is indeterminate when it blows up so not the same line or number of iterations each time.  I am guessing that it is related to when the GC kicks in.  Perhaps that has something to do with the weak references.  I don't know, I am guessing.  I tried switching to hard references but I got a different error that I wasn't expecting.  I need to spend more time studying that code.

**Comment by nickl-** [comment]
Not entirely sure whether this falls under memory leaks or namespace issues, both are more specific then this lets on.

Suggest we keep this as a separate issue until we can pinpoint a root cause.

**Comment by opeongo** [comment]
btw not fixed

**Comment by nickl-** [comment]
Not sure why this was closed...

> Not sure if this resolves #655, lacking a root cause analysis or unit test, since this issue specifically pertains to the dot notation in references.

Probably bad choice of words in the PR description.

I think the words are...

fix
fixes
fixed
resolve
resolves
resolved

...followed by the issue number. But I thought it was just in commit messages. Will need to keep an eye on this.

**Comment by opeongo** [comment]
Still an issue after this latest merge, as tested with a real life data processing workload

**Comment by nickl-** [comment]
do you have a stack trace or anything useful to help track this down?

Can we do mock data perhaps to try and run in separately?

**Comment by opeongo** [comment]
See new unit tests in 45ab8604 that should expose the problem

**Comment by nickl-** [comment]
> See new unit tests in [45ab860](https://github.com/beanshell/beanshell/commit/45ab86047995c655176f93f98a9589a0f5154420) that should expose the problem

I don't see what these tests are trying to prove. If you don't want `x = 5` to be considered then I would think that the logical solution will be to remove it. Nor do I see how these tests are proving why variables are disappearing with the long running script. To assume on a hunch that if someone spends time and effort that it might prove something callous and frankly I find it rude.

Unless something changes on this issue I see no other recourse then to close it as: cannot be reproduced.

**Comment by nickl-** [comment]
Would've been nice to know why the unit tests are applicable, it would've made finding the fix easier.

#679 fixed prematurely clearing block name space after use, which allows for successfully running the above mentioned unit tests. We are also using soft references in the block name space cache which will help retain recently used references, along with the blocks actually being cached instead of having no reference, should just improve accessibility of state from  these "created but only used later" blocks.

Crossing fingers that this issue is also now resolved.

**Comment by nickl-** [comment]
Closed: cannot reproduce...until further notice

**Comment by opeongo** [comment]
This is fixed by PR #741

**Comment by nickl-** [comment]
Reopened pending PR review

**Comment by jimjag** [comment]
In January 2024 this was reported as fixed by #741, and reopened pending review of that PR. #741 is now merged on master as part of #789 (c8aac59d).

On current master a stress script modeled on the report (200,000 calls to a scripted method that loops over array parameters and returns `this`, in a 64 MB heap, with soft and weak references forcibly reclaimed every 40,000 calls) completed without errors.

Closing as fixed; please reopen if it recurs with your real workload on a build that includes #789.
